# Generated by Django 2.2 on 2020-10-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/documents/index.png', null=True, upload_to='', verbose_name='تصویر پروفایل'),
        ),
    ]
